export type VocabCategory = 'stationery' | 'kitchen' | 'house' | 'other'

/**
 * A simple example sentence generated by Monlam chat for a word. No
 * fill-in-blank quiz structure (no distractors) — dynamically generated
 * sentences aren't curated with wrong-answer options, so Sentence Practice
 * shows these as read/listen examples rather than a multiple-choice quiz.
 */
export interface SentenceItem {
  english: string
  tibetan: string
  audioUrl?: string
}

export interface VocabularyItem {
  id: string
  english: string
  tibetan: string
  /** true when sourced from Monlam's dictionary (+ LLM sense-check) or manually verified — false only for offline-demo placeholders */
  verified: boolean
  category: VocabCategory
  difficulty: number
  emoji: string
  imageUrl?: string
  audioUrl?: string
  sentences: SentenceItem[]
}

export type LearningEventType =
  | 'object_identified'
  | 'word_viewed'
  | 'audio_played'
  | 'trace_started'
  | 'trace_completed'
  | 'sentence_viewed'
  | 'sentence_answered'
  | 'mission_started'
  | 'mission_completed'
  | 'nfc_detected'
  | 'nfc_audio_played'

export interface LearningEvent {
  vocabularyId: string
  eventType: LearningEventType
  source: 'web' | 'nfc'
  timestamp: number
  meta?: Record<string, unknown>
}

/** Missions target a category + count, not specific words — any recognized
 * item in that category counts (including synonyms/variants), and the
 * category set is developer-defined (see data/missions.ts), not dynamic. */
export interface Mission {
  id: string
  title: string
  description: string
  targetCategory: VocabCategory
  requiredCount: number
  reward: number
  badge: string
}

export interface UserProgress {
  stars: number
  level: number
  badges: string[]
  unlockedAreas: string[]
  wordStats: Record<string, { heard: number; traced: number; found: number; nfc: number; quiz: number }>
  /** Every word ever discovered, cached locally — dynamic discovery has no
   * static array to look words up in, so this is the source of truth for
   * WordDetail/Tracing/SentenceQuiz/Learn-tab/Mission-category-matching. */
  discoveredWords: Record<string, VocabularyItem>
}

export interface RecognitionResult {
  object: string
  category: VocabCategory
  confidence: number
}

/** Result of POST /api/discover — three possible shapes depending on `status`. */
export type DiscoverResult =
  | { status: 'low_confidence'; object: string; category: VocabCategory; confidence: number }
  | { status: 'not_in_dictionary'; object: string; category: VocabCategory; confidence: number }
  | ({ status: 'ok' } & VocabularyItem)
