// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfnB9wt5A8dCu_Qih4pTULrKuT_Yba8U',
    appId: '1:949191680600:web:cc7e31d9540668a574e02d',
    messagingSenderId: '949191680600',
    projectId: 'tashi-learn',
    authDomain: 'tashi-learn.firebaseapp.com',
    storageBucket: 'tashi-learn.firebasestorage.app',
    measurementId: 'G-N9KP27F9ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESbXtIL1SE3U5bLvOW9lmMImDt3nWULs',
    appId: '1:949191680600:android:019558bdbf1a052074e02d',
    messagingSenderId: '949191680600',
    projectId: 'tashi-learn',
    storageBucket: 'tashi-learn.firebasestorage.app',
  );
}
